services:
  - type: web
    name: code-playground-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JUDGE0_API_URL
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CORS_ALLOWED_METHODS
        sync: false
      - key: CORS_ALLOWED_HEADERS
        sync: false
      - key: PORT
        sync: false
