server.port=8081
judge0.api.url=https://judge0-ce.p.rapidapi.com
judge0.api.key=b672286a71mshdaf8715b85423dfp1525ddjsn9bfa2b0cf258

# CORS Configuration
cors.allowed-origins=https://codeatsanjays-code-playgrounds.netlify.app
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*


# Disable DevTools auto-restart
spring.devtools.restart.enabled=false

# Increase timeout settings
spring.mvc.async.request-timeout=3600000

# Increase server connection timeout
server.connection-timeout=3600000

# Increase tomcat settings
server.tomcat.connection-timeout=3600000
server.tomcat.keep-alive-timeout=3600000

# Disable session timeout
server.servlet.session.timeout=0
