server.port=${PORT:8080}
judge0.api.url=${JUDGE0_API_URL}
judge0.api.key=${JUDGE0_API_KEY}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
cors.allowed-methods=${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
cors.allowed-headers=${CORS_ALLOWED_HEADERS:*}


# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.codeplayground=DEBUG
